# Generated by Django 6.0.3 on 2026-09-04 16:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('wallet', 'Self-custody wallet address'), ('coinbase', 'Coinbase deposit address'), ('robinhood', 'Robinhood deposit address'), ('exchange', 'Other exchange deposit address')], default='wallet', max_length=32)),
                ('address', models.CharField(max_length=256)),
                ('chain', models.CharField(default='base', max_length=64)),
                ('asset_symbol', models.CharField(default='USDC', max_length=32)),
                ('share', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_net_profit_usd', models.DecimalField(decimal_places=6, default=Decimal('50.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_transfer_usd', models.DecimalField(decimal_places=6, default=Decimal('5.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reserve_usd', models.DecimalField(decimal_places=6, default=Decimal('20.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('enabled', models.BooleanField(default=True)),
                ('auto_send', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('qualifying_profit_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('profit_window_start_ts', models.FloatField()),
                ('profit_window_end_ts', models.FloatField()),
                ('trades_counted', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Computed, awaiting send'), ('skipped', 'Below threshold or reserve'), ('sent', 'Broadcast on chain'), ('failed', 'Send failed')], default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=256)),
                ('tx_hash', models.CharField(blank=True, max_length=128)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payouts.payoutdestination')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destination', 'status'], name='payouts_pay_destina_95f761_idx'), models.Index(fields=['profit_window_end_ts'], name='payouts_pay_profit__580576_idx')],
            },
        ),
    ]
