# Generated by Django 5.1.4 on 2025-11-27 23:41

import branddozer.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('root_path', models.TextField()),
                ('default_prompt', models.TextField(blank=True, default='')),
                ('interjections', models.JSONField(blank=True, default=list)),
                ('interval_minutes', models.PositiveIntegerField(default=120)),
                ('enabled', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_ai_generated', models.DateTimeField(blank=True, null=True)),
                ('log_path', models.TextField(default=branddozer.models._default_log_path)),
                ('repo_url', models.TextField(blank=True, default='')),
                ('repo_branch', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
