# Generated by Django 5.1.4 on 2026-01-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branddozer', '0003_background_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysession',
            name='role',
            field=models.CharField(choices=[('orchestrator', 'Orchestrator'), ('pm', 'Project Manager Session'), ('integrator', 'Integrator/Release Session'), ('dev', 'CodexSession'), ('qa', 'QA'), ('ux_audit', 'UX Audit')], default='dev', max_length=32),
        ),
    ]
