# Generated by Django 6.0.3 on 2026-04-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branddozer', '0004_alter_deliverysession_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysession',
            name='role',
            field=models.CharField(choices=[('orchestrator', 'Orchestrator'), ('pm', 'Project Manager Session'), ('integrator', 'Integrator/Release Session'), ('dev', 'C0d3rV2Session'), ('qa', 'QA'), ('ux_audit', 'UX Audit')], default='dev', max_length=32),
        ),
    ]
