# Generated by Django 5.1.4 on 2026-02-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('parser_config', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_sources',
                'indexes': [models.Index(fields=['active', 'updated_at'], name='news_source_active_61f830_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsSourceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='datalab.newssource')),
            ],
            options={
                'db_table': 'news_source_articles',
                'indexes': [models.Index(fields=['source', 'created_at'], name='news_source_source__99663d_idx')],
            },
        ),
    ]
