# Generated by Django 5.1.4 on 2026-02-08 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OhlcvDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=32)),
                ('symbol', models.CharField(max_length=64)),
                ('granularity_seconds', models.PositiveIntegerField(default=300)),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('bars', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='download2000', max_length=64)),
                ('file_path', models.TextField(blank=True, default='')),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_ingested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ohlcv_ingests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ohlcv_datasets',
            },
        ),
        migrations.CreateModel(
            name='OhlcvBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField(default=0.0)),
                ('buy_volume', models.FloatField(default=0.0)),
                ('sell_volume', models.FloatField(default=0.0)),
                ('net_volume', models.FloatField(default=0.0)),
                ('vwap', models.FloatField(default=0.0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars_data', to='datalab.ohlcvdataset')),
            ],
            options={
                'db_table': 'ohlcv_bars',
            },
        ),
        migrations.AddIndex(
            model_name='ohlcvdataset',
            index=models.Index(fields=['chain', 'symbol', 'granularity_seconds'], name='ohlcv_datas_chain_ea8f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcvdataset',
            index=models.Index(fields=['start_ts', 'end_ts'], name='ohlcv_datas_start_t_751d7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ohlcvdataset',
            unique_together={('chain', 'symbol', 'granularity_seconds', 'start_ts', 'end_ts')},
        ),
        migrations.AddIndex(
            model_name='ohlcvbar',
            index=models.Index(fields=['dataset', 'ts'], name='ohlcv_bars_dataset_028535_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcvbar',
            index=models.Index(fields=['ts'], name='ohlcv_bars_ts_408e75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ohlcvbar',
            unique_together={('dataset', 'ts')},
        ),
    ]
