# Generated by Django 5.1.4 on 2025-11-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securevault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securesetting',
            name='tag',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
