# Generated by Django 5.1.4 on 2026-02-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='walletnftpreference',
            new_name='walletpanel_user_id_01aaa9_idx',
            old_name='walletpanel_user_id_chain_idx',
        ),
        migrations.RenameIndex(
            model_name='walletnftpreference',
            new_name='walletpanel_user_id_715ec1_idx',
            old_name='walletpanel_user_id_contract_idx',
        ),
    ]
