# Generated by Django 5.1.4 on 2025-12-05 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u53rxr080t', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
