# Generated by Django 6.0.3 on 2026-09-04 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch. Off means the agent does nothing.')),
                ('tier', models.CharField(choices=[('ghost', 'Ghost (no real money)'), ('micro', 'Micro ($0.25 clips)'), ('small', 'Small ($0.75 clips)'), ('normal', 'Normal (full size)')], default='ghost', max_length=16)),
                ('agent', models.CharField(default='claude', max_length=32)),
                ('interval_sec', models.IntegerField(default=900)),
                ('max_daily_loss_usd', models.FloatField(default=2.0, help_text='Stop trading for the day past this.')),
                ('max_open_positions', models.IntegerField(default=3)),
                ('max_tokens_tracked', models.IntegerField(default=25)),
                ('halted_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent configuration',
                'verbose_name_plural': 'Agent configuration',
            },
        ),
        migrations.CreateModel(
            name='LossRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.TextField(help_text="The situation, e.g. 'position is down 3% within 10 minutes'.")),
                ('action', models.TextField(help_text="What to do, e.g. 'exit half, hold the rest to the stop'.")),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='proposed', max_length=16)),
                ('times_triggered', models.IntegerField(default=0)),
                ('avg_loss_without', models.FloatField(default=0.0, help_text='Average loss on comparable trades without it.')),
                ('avg_loss_with', models.FloatField(default=0.0, help_text='Average loss when this rule fired.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'loss recoveries',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(db_index=True, default='claude', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rate_limited', 'Rate limited')], db_index=True, default='running', max_length=16)),
                ('prompt', models.TextField(blank=True)),
                ('report', models.TextField(blank=True)),
                ('observations', models.JSONField(blank=True, default=dict)),
                ('tokens_considered', models.JSONField(blank=True, default=list)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('trades_opened', models.IntegerField(default=0)),
                ('trades_closed', models.IntegerField(default=0)),
                ('net_pl', models.FloatField(default=0.0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('score', models.FloatField(default=0.0)),
                ('score_parts', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['status', '-started_at'], name='tradingagen_status_8b8cf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(help_text='The rule, stated so it can be checked against a trade.')),
                ('kind', models.CharField(choices=[('entry', 'When to enter'), ('exit', 'When to exit'), ('sizing', 'How much to risk'), ('token', 'Which tokens to trade'), ('timing', 'When to trade at all'), ('recovery', 'How to recover a loss')], db_index=True, default='entry', max_length=16)),
                ('status', models.CharField(choices=[('proposed', 'Proposed (not yet tested)'), ('active', 'Active (in force)'), ('suspended', 'Suspended (stopped paying)'), ('retired', 'Retired (disproven)')], db_index=True, default='proposed', max_length=16)),
                ('rationale', models.TextField(blank=True, help_text='Why the agent believes this, with the numbers.')),
                ('trades_under', models.IntegerField(default=0)),
                ('net_pl_under', models.FloatField(default=0.0)),
                ('win_rate_under', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constraints_created', to='tradingagent.agentrun')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothesis', models.TextField(help_text='What the agent thinks is true, stated so it can be wrong.')),
                ('metric', models.CharField(default='net_pl', help_text='The number that decides it: net_pl, win_rate, profit_factor.', max_length=64)),
                ('target', models.FloatField(default=0.0, help_text='What the metric must reach to confirm.')),
                ('min_trades', models.IntegerField(default=20, help_text='Sample below which the result is noise.')),
                ('status', models.CharField(choices=[('designed', 'Designed'), ('ghost', 'Running in ghost'), ('live', 'Graduated to live'), ('confirmed', 'Confirmed (hypothesis held)'), ('refuted', 'Refuted (hypothesis failed)'), ('abandoned', 'Abandoned')], db_index=True, default='designed', max_length=16)),
                ('tier', models.CharField(choices=[('ghost', 'Ghost (no real money)'), ('micro', 'Micro ($0.25 clips)'), ('small', 'Small ($0.75 clips)'), ('normal', 'Normal (full size)')], db_index=True, default='ghost', max_length=16)),
                ('ghost_trades', models.IntegerField(default=0)),
                ('ghost_net_pl', models.FloatField(default=0.0)),
                ('live_trades', models.IntegerField(default=0)),
                ('live_net_pl', models.FloatField(default=0.0)),
                ('max_loss_usd', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('constraint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='tradingagent.constraint')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddIndex(
            model_name='constraint',
            index=models.Index(fields=['status', 'kind'], name='tradingagen_status_59079b_idx'),
        ),
    ]
