# Generated by Django 6.0.3 on 2026-09-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingagent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='start_at_boot',
            field=models.BooleanField(default=True, help_text='Start the agent worker automatically when the machine boots. Turn off to start it by hand instead.'),
        ),
    ]
