from __future__ import annotations

from typing import Dict, List

SECURE_SETTINGS_CATALOG: List[Dict[str, object]] = [
    {"name": "MNEMONIC", "category": "default", "is_secret": True, "label": "Wallet Mnemonic"},
    {"name": "PRIVATE_KEY", "category": "default", "is_secret": True, "label": "Wallet Private Key"},
    {"name": "DERIVATION_PATH", "category": "default", "is_secret": False, "label": "Derivation Path"},
    {"name": "WALLET_LIVE", "category": "default", "is_secret": False, "label": "Live Wallet Indicator"},
    {"name": "ALCHEMY_API_KEY", "category": "default", "is_secret": True, "label": "Alchemy API Key"},
    {"name": "ALCHEMY_KEY_BASE", "category": "default", "is_secret": True, "label": "Alchemy Secondary Key"},
    {"name": "INFURA_API_KEY", "category": "default", "is_secret": True, "label": "Infura API Key"},
    {"name": "RPC_ETHEREUM", "category": "default", "is_secret": False, "label": "RPC URL · Ethereum"},
    {"name": "RPC_BASE", "category": "default", "is_secret": False, "label": "RPC URL · Base"},
    {"name": "RPC_ARB", "category": "default", "is_secret": False, "label": "RPC URL · Arbitrum"},
    {"name": "RPC_OP", "category": "default", "is_secret": False, "label": "RPC URL · Optimism"},
    {"name": "RPC_POLY", "category": "default", "is_secret": False, "label": "RPC URL · Polygon"},
    {"name": "ALCHEMY_ETH_URL", "category": "default", "is_secret": False, "label": "Alchemy ETH URL"},
    {"name": "ALCHEMY_BASE_URL", "category": "default", "is_secret": False, "label": "Alchemy Base URL"},
    {"name": "ALCHEMY_ARB_URL", "category": "default", "is_secret": False, "label": "Alchemy Arbitrum URL"},
    {"name": "ALCHEMY_OP_URL", "category": "default", "is_secret": False, "label": "Alchemy OP URL"},
    {"name": "ALCHEMY_POLY_URL", "category": "default", "is_secret": False, "label": "Alchemy Polygon URL"},
    {"name": "INFURA_ETH_URL", "category": "default", "is_secret": False, "label": "Infura ETH URL"},
    {"name": "INFURA_ARB_URL", "category": "default", "is_secret": False, "label": "Infura Arbitrum URL"},
    {"name": "INFURA_OP_URL", "category": "default", "is_secret": False, "label": "Infura OP URL"},
    {"name": "INFURA_POLY_URL", "category": "default", "is_secret": False, "label": "Infura Polygon URL"},
    {"name": "ALCHEMY_TIMEOUT_SEC", "category": "default", "is_secret": False, "label": "Alchemy Timeout (s)"},
    {"name": "HTTP_TIMEOUT_SEC", "category": "default", "is_secret": False, "label": "HTTP Timeout (s)"},
    {"name": "TX_TIMEOUT_SEC", "category": "default", "is_secret": False, "label": "Tx Timeout (s)"},
    {"name": "PORTFOLIO_REORG_SAFETY", "category": "default", "is_secret": False, "label": "Portfolio Reorg Safety"},
    {"name": "CRYPTOPANIC_API_KEY", "category": "default", "is_secret": True, "label": "CryptoPanic API Key"},
    {"name": "CRYPTOPANIC_MAX_CALLS_PER_MIN", "category": "default", "is_secret": False, "label": "CryptoPanic Max Calls"},
    {"name": "MARKET_DATA_COINGECKO_IDS", "category": "default", "is_secret": False, "label": "CoinGecko IDs"},
    {"name": "ANKR_API_KEY", "category": "default", "is_secret": True, "label": "Ankr API Key"},
    {"name": "ZEROX_API_KEY", "category": "default", "is_secret": True, "label": "0x API Key"},
    {"name": "ONEINCH_API_KEY", "category": "default", "is_secret": True, "label": "1inch API Key"},
    {"name": "LIFI_API_KEY", "category": "default", "is_secret": True, "label": "LI.FI API Key"},
    {"name": "LIFI_BASE", "category": "default", "is_secret": False, "label": "LI.FI Base URL"},
    {"name": "THEGRAPH_API_KEY", "category": "default", "is_secret": True, "label": "The Graph API Key"},
    {"name": "UNISWAP_SUBGRAPH_ETHEREUM", "category": "default", "is_secret": False, "label": "Uniswap Subgraph · ETH"},
    {"name": "UNISWAP_SUBGRAPH_BASE", "category": "default", "is_secret": False, "label": "Uniswap Subgraph · Base"},
    {"name": "UNISWAP_SUBGRAPH_ARBITRUM", "category": "default", "is_secret": False, "label": "Uniswap Subgraph · Arbitrum"},
    {"name": "UNISWAP_SUBGRAPH_OPTIMISM", "category": "default", "is_secret": False, "label": "Uniswap Subgraph · Optimism"},
    {"name": "UNISWAP_SUBGRAPH_POLYGON", "category": "default", "is_secret": False, "label": "Uniswap Subgraph · Polygon"},
    {"name": "WNATIVE_ETHEREUM", "category": "default", "is_secret": False, "label": "WETH Address"},
    {"name": "WNATIVE_BASE", "category": "default", "is_secret": False, "label": "WETH (Base) Address"},
    {"name": "WNATIVE_ARBITRUM", "category": "default", "is_secret": False, "label": "WETH (Arbitrum) Address"},
    {"name": "WNATIVE_OPTIMISM", "category": "default", "is_secret": False, "label": "WETH (OP) Address"},
    {"name": "WNATIVE_POLYGON", "category": "default", "is_secret": False, "label": "WMATIC Address"},
    {"name": "ETH_USDC_ADDR", "category": "default", "is_secret": False, "label": "USDC · Ethereum"},
    {"name": "BASE_USDC_ADDR", "category": "default", "is_secret": False, "label": "USDC · Base"},
    {"name": "ARB_USDC_ADDR", "category": "default", "is_secret": False, "label": "USDC · Arbitrum"},
    {"name": "OP_USDC_ADDR", "category": "default", "is_secret": False, "label": "USDC · Optimism"},
    {"name": "POLY_USDC_ADDR", "category": "default", "is_secret": False, "label": "USDC · Polygon"},
    {"name": "POLY_USDCe_ADDR", "category": "default", "is_secret": False, "label": "USDC.e · Polygon"},
    {"name": "AUTO_WRAP_NATIVE", "category": "default", "is_secret": False, "label": "Auto Wrap Native"},
    {"name": "APPROVE_MODE", "category": "default", "is_secret": False, "label": "Approve Mode"},
    {"name": "PRICE_UNISWAP", "category": "default", "is_secret": False, "label": "Price · Uniswap"},
    {"name": "PRICE_TTL_SEC", "category": "default", "is_secret": False, "label": "Price Cache TTL"},
    {"name": "PRICE_MAX_TOKENS", "category": "default", "is_secret": False, "label": "Price Max Tokens"},
    {"name": "PRICE_WORKERS", "category": "default", "is_secret": False, "label": "Price Workers"},
    {"name": "FILTER_SCAMS", "category": "default", "is_secret": False, "label": "Filter Scams"},
    {"name": "SCAM_STRICT", "category": "default", "is_secret": False, "label": "Scam Strict Mode"},
    {"name": "SCAM_MIN_LIQ_USD", "category": "default", "is_secret": False, "label": "Scam Min Liquidity"},
    {"name": "SCAM_MAX_TAX_PCT", "category": "default", "is_secret": False, "label": "Scam Max Tax"},
    {"name": "SCAM_USE_GOPLUS", "category": "default", "is_secret": False, "label": "Use GoPlus"},
    {"name": "BLOCKSCOUT_INCLUDE_UNVERIFIED", "category": "default", "is_secret": False, "label": "Blockscout Unverified"},
    {"name": "GOPLUS_APP_KEY", "category": "default", "is_secret": True, "label": "GoPlus App Key"},
    {"name": "GOPLUS_APP_SECRET", "category": "default", "is_secret": True, "label": "GoPlus App Secret"},
    {"name": "COINGECKO_API_KEY", "category": "default", "is_secret": True, "label": "CoinGecko API Key"},
    {"name": "BRAVE_API_KEY", "category": "default", "is_secret": True, "label": "Brave Search API Key"},
    {"name": "C0D3R_SESSION_BUCKET", "category": "default", "is_secret": False, "label": "c0d3r Session S3 Bucket"},
    {"name": "C0D3R_SESSION_REGION", "category": "default", "is_secret": False, "label": "c0d3r Session S3 Region"},
    {"name": "C0D3R_SESSION_PREFIX", "category": "default", "is_secret": False, "label": "c0d3r Session S3 Prefix"},
    {"name": "C0D3R_SESSION_MODE", "category": "default", "is_secret": False, "label": "c0d3r Session Storage Mode"},
]

CATALOG_LOOKUP = {
    (entry["category"].lower(), entry["name"]): entry for entry in SECURE_SETTINGS_CATALOG
}
