from __future__ import annotations

DEFAULT_GUARDIAN_PROMPT = (
    "Instructions:\n"
    "• Do not modify any files under monitoring_guardian/ or tools/codex_session.py; treat them as read-only infrastructure.\n"
    "• You cannot access external networks or run git push from this sandbox; never attempt those operations—just note it for the operator if needed.\n"
    "1. Fix any errors found in the logs by making meaningful upgrades while following a fix/test/fix/test loop.\n"
    "2. Answer the following question:\n"
    "\"What are 15 improvements to make for this system to (A) enhance it toward equilibrium in producing the most accurate crypto price and "
    "volume predictions for windows from 5 minutes to 6 months—from the current data stream onward—while finding buy-low/sell-high opportunities "
    "and scheduling them in ghost and live trading with 15% of each profitable swap flowing into stablecoin savings once Nash equilibrium is "
    "reached; (B) operate efficiently on an i5 CPU with 32GB RAM without downgrading functionality or accuracy—only more efficient engineering; "
    "(C) draw on additional ethical, free news sources at arbitrary dates, scrape/store them per design, and inject them into model training; "
    "(D) Try to get ghost trading to start trading accurately sooner than later and let it become more accurate as the system evolves. To such a "
    "point that live trading kicks in on what it is doing. We want to get live trading to start as soon as possible, but it does need some pretty "
    "decent degree of accuracy. Where can you be accurate most of the time with what changes? Make sure to validate your solution by testing "
    "predictions in confusion matrices if you use classification such as predicting an upward climb or a downward fall, and try to integrate that "
    "with other metrics to find a margin, for example, but you could also test it on historical ohlcv data we already have if you are using "
    "regression, and refine as needed before implementing. Try to expand your horizons all across the ML domain keeping it to methods that will "
    "run on a pc with a core i5 cpu and 32 GB of ram and no dedicated GPU with CUDA (E) how can we improve the Django website/command center to "
    "show more of what is happening in the trading bot system and implement tools that will help us visualize new outcomes and experiment with "
    "refining accuracy and collecting meaningful data for the system to ingest. How can we demonstrate all of this better within the organism 3D "
    "area to show the processes and data and where they are in snapshots and cluster them better in the visualization to push it to make it more "
    "energetic and biology-like pushing our ability to run the snapshots in a sequence one after the other and show a vast network of processes "
    "working to predict crypto prices and volume and trade accurately. (F) how can we upgrade the swarm? (G) how can we coordinate the transition "
    "of swaps in ghost and live trading for higher gains and lower risks? fix errors as you go using a fix/test loop running all relevant unit tests "
    "for changed components).\"\n"
    "3. Implement those improvements.\n"
    "4. After each fix, run the relevant tests (unit tests, lab regression, etc.) and report the results.\n"
    "5. Stop only after all items are addressed or when manual approval is required.\n"
    "6. Make sure to update the .gitignore if you add anything that creates many downloaded files like node_modules, insecure information to release "
    "to the public, or anything else a .gitignore entry would be qualified for.\n"
    "7. Start main.py and option 7 again. make sure the program is running before you stop, because it has to start using the upgrades as soon as "
    "possible to gather data on how it is working. Don't shut the program back down before you stop working. Let it run.\n"
    "8. Make sure not to touch anything in the monitoring_guardian folder or tools/codex_session.py as you are working.\n"
)
