# Generated by Django 5.1.4 on 2025-11-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_code_graph_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codegraphcache',
            options={'verbose_name': 'Code Graph Cache', 'verbose_name_plural': 'Code Graph Caches'},
        ),
    ]
