# Generated by Django 5.1.4 on 2025-11-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trading_tables'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advisory',
            index=models.Index(fields=['resolved', 'ts'], name='advisories_resolve_051b73_idx'),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['wallet', 'chain'], name='balances_wallet_eb14f8_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackevent',
            index=models.Index(fields=['source', 'ts'], name='feedback_ev_source_8a8567_idx'),
        ),
        migrations.AddIndex(
            model_name='marketstream',
            index=models.Index(fields=['symbol', 'chain'], name='market_stre_symbol_15c2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='marketstream',
            index=models.Index(fields=['ts'], name='market_stre_ts_444a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='metricentry',
            index=models.Index(fields=['stage', 'ts'], name='metrics_stage_e45ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='metricentry',
            index=models.Index(fields=['category'], name='metrics_categor_911173_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['is_active'], name='model_versi_is_acti_e7e66d_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['chain', 'token'], name='prices_chain_f85054_idx'),
        ),
        migrations.AddIndex(
            model_name='tradefill',
            index=models.Index(fields=['symbol', 'chain'], name='trade_fills_symbol_506ced_idx'),
        ),
        migrations.AddIndex(
            model_name='tradefill',
            index=models.Index(fields=['ts'], name='trade_fills_ts_e5d380_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingop',
            index=models.Index(fields=['ts'], name='trading_ops_ts_a58f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingop',
            index=models.Index(fields=['wallet', 'chain'], name='trading_ops_wallet_7666db_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['wallet', 'chain'], name='transfers_wallet_62966d_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['token'], name='transfers_token_81f380_idx'),
        ),
    ]
