# Generated by Django 5.1.4 on 2026-02-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_knowledge_matrix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equation',
            new_name='equations_created_d0189c_idx',
            old_name='equations_created_95a7e2_idx',
        ),
        migrations.RenameIndex(
            model_name='equationlink',
            new_name='equation_li_relatio_e5f019_idx',
            old_name='equation_l_relation_1a7a60_idx',
        ),
        migrations.RenameIndex(
            model_name='unboundedmatrixrecord',
            new_name='unbounded_m_created_18e5e3_idx',
            old_name='unbounded_m_created_d9b6a1_idx',
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knowledgequeueitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labelqueueitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='techmatrixrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visuallabelqueueitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
