# Generated by Django 5.1.4 on 2026-02-07 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_equation_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='C0d3rWebSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c0d3r_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'c0d3r_web_sessions',
            },
        ),
        migrations.CreateModel(
            name='C0d3rWebMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=24)),
                ('content', models.TextField(blank=True, default='')),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.c0d3rwebsession')),
            ],
            options={
                'db_table': 'c0d3r_web_messages',
            },
        ),
        migrations.AddIndex(
            model_name='c0d3rwebsession',
            index=models.Index(fields=['user', 'last_active'], name='c0d3r_web_s_user_id_df30da_idx'),
        ),
        migrations.AddIndex(
            model_name='c0d3rwebmessage',
            index=models.Index(fields=['session', 'created_at'], name='c0d3r_web_m_session_518e4a_idx'),
        ),
    ]
