# Generated by Django 5.1.4 on 2026-02-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_c0d3rwebsession_c0d3rwebmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=128)),
                ('severity', models.CharField(default='info', max_length=32)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_logs',
                'indexes': [models.Index(fields=['component', 'created_at'], name='system_logs_compone_590e18_idx'), models.Index(fields=['created_at'], name='system_logs_created_2e006d_idx')],
            },
        ),
    ]
