# Generated by Django 5.1.4 on 2025-11-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64, unique=True)),
                ('chain', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('honeypot', 'Honeypot'), ('rejected', 'Rejected'), ('promoted', 'Promoted')], default='pending', max_length=32)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='discovery_d_status_213421_idx'), models.Index(fields=['chain'], name='discovery_d_chain_aef637_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=64)),
                ('chain', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(max_length=128)),
                ('bull_score', models.FloatField(blank=True, null=True)),
                ('bear_score', models.FloatField(blank=True, null=True)),
                ('liquidity_usd', models.FloatField(blank=True, null=True)),
                ('volume_24h', models.FloatField(blank=True, null=True)),
                ('price_change_24h', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'chain'], name='discovery_d_symbol_c12419_idx'), models.Index(fields=['created_at'], name='discovery_d_created_99dc7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HoneypotCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=64)),
                ('chain', models.CharField(blank=True, max_length=64, null=True)),
                ('verdict', models.CharField(max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'chain'], name='discovery_h_symbol_b4816d_idx'), models.Index(fields=['created_at'], name='discovery_h_created_29c988_idx')],
            },
        ),
        migrations.CreateModel(
            name='SwapProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=64)),
                ('chain', models.CharField(blank=True, max_length=64, null=True)),
                ('buy_tx_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('sell_tx_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('buy_amount', models.FloatField(blank=True, null=True)),
                ('sell_amount', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('gas_cost_native', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'chain'], name='discovery_s_symbol_8cdf91_idx'), models.Index(fields=['created_at'], name='discovery_s_created_e73c1c_idx')],
            },
        ),
    ]
