from __future__ import annotations

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "core"

urlpatterns = [
    path("", views.LandingView.as_view(), name="index"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("signup", views.SignupView.as_view()),
    path("logout/", auth_views.LogoutView.as_view(next_page="core:index"), name="logout"),
    path("logout", auth_views.LogoutView.as_view(next_page="core:index")),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("dashboard", views.DashboardView.as_view()),
    path("organism/", views.OrganismView.as_view(), name="organism"),
    path("organism", views.OrganismView.as_view()),
    path("streams/", views.StreamsView.as_view(), name="streams"),
    path("streams", views.StreamsView.as_view()),
    path("telemetry/", views.TelemetryView.as_view(), name="telemetry"),
    path("telemetry", views.TelemetryView.as_view()),
    path("wallet/", views.WalletPageView.as_view(), name="wallet"),
    path("wallet", views.WalletPageView.as_view()),
    path("pipeline/", views.PipelinePageView.as_view(), name="pipeline"),
    path("pipeline", views.PipelinePageView.as_view()),
    path("datalab/", views.DataLabPageView.as_view(), name="datalab"),
    path("datalab", views.DataLabPageView.as_view()),
    path("lab/", views.ModelLabPageView.as_view(), name="lab"),
    path("lab", views.ModelLabPageView.as_view()),
    path("guardian/", views.GuardianPageView.as_view(), name="guardian"),
    path("guardian", views.GuardianPageView.as_view()),
    path("guardian/fallback/", views.GuardianFallbackView.as_view(), name="guardian-fallback"),
    path("guardian/fallback", views.GuardianFallbackView.as_view()),
    path("settings/", views.SecureSettingsPageView.as_view(), name="settings"),
    path("settings", views.SecureSettingsPageView.as_view()),
    path("addressbook/", views.AddressBookPageView.as_view(), name="addressbook"),
    path("addressbook", views.AddressBookPageView.as_view()),
    path("c0d3r/", views.C0d3rPageView.as_view(), name="c0d3r"),
    path("c0d3r", views.C0d3rPageView.as_view()),
    path("integrations/", views.IntegrationsPageView.as_view(), name="integrations"),
    path("integrations", views.IntegrationsPageView.as_view()),
    path("codegraph/", views.CodeGraphPageView.as_view(), name="codegraph"),
    path("codegraph", views.CodeGraphPageView.as_view()),
    path("branddozer/", views.BrandDozerPageView.as_view(), name="branddozer"),
    path("branddozer", views.BrandDozerPageView.as_view()),
    path("branddozer/solo/", views.BrandDozerSoloView.as_view(), name="branddozer-solo"),
    path("branddozer/solo", views.BrandDozerSoloView.as_view()),
    path("u53rxr080t/", views.U53RxRobotPageView.as_view(), name="u53rxr080t"),
    path("u53rxr080t", views.U53RxRobotPageView.as_view()),
    path("audiolab/", views.AudioLabPageView.as_view(), name="audiolab"),
    path("audiolab", views.AudioLabPageView.as_view()),
    path("api/codegraph/", views.CodeGraphDataView.as_view(), name="codegraph-data"),
    path("api/codegraph", views.CodeGraphDataView.as_view()),
    path("api/codegraph/snapshots/", views.CodeGraphSnapshotView.as_view(), name="codegraph-snapshots"),
    path("api/codegraph/snapshots", views.CodeGraphSnapshotView.as_view()),
    path("api/codegraph/files/", views.CodeGraphFilesView.as_view(), name="codegraph-files"),
    path("api/codegraph/files", views.CodeGraphFilesView.as_view()),
    path("api/c0d3r/run/", views.C0d3rRunView.as_view(), name="c0d3r-run"),
    path("api/c0d3r/run", views.C0d3rRunView.as_view()),
    path("advisories/", views.AdvisoriesPageView.as_view(), name="advisories"),
    path("advisories", views.AdvisoriesPageView.as_view()),
    path("<slug:route>/", views.SpaRouteView.as_view(), name="spa-route"),
    path("<slug:route>", views.SpaRouteView.as_view()),
]
