"""tools/wizard_session.py — W1z4rD brain server AI backend.

Drop-in AI session that calls the brain server's /chat endpoint
(W1z4rDV1510n crates/brain, port 8095 default).  Matches the send()
interface used by C0d3rSession so it can be swapped in anywhere
sessions are created.

The brain uses Hebbian neural fabric — answers are recalled from
trained associations, not generated by a transformer.  This means:
  - Responses improve as the brain trains on more data.
  - Structured JSON requests may not return valid JSON until training
    covers the requested format.
  - The agent's fallback mechanisms handle empty/hypothesis responses.

Endpoint contract (brain_server.rs, W1z4rDV1510n crates/node):
  POST /chat
  Request:  {"text": str}
  Response: {
    "reply": str,          # primary recalled answer (alias of `answer`)
    "answer": str,         # same; kept for compatibility
    "decoder": str,        # "multi_pool" | "char_chain" | "eem"
    "predictions": {pool_name: [labels]},
    "grounding": {
      "fabric_confidence": f32,
      "integrated_confidence": f32,
      "outside_grounding": bool,
      "speculation_flag": bool,
    },
    "activated_concepts": [str]
  }

Cluster mode: when the brain runs in §18 cluster mode (multiple ring
members), the head's /chat already aggregates from workers via the
demand-paged TieredStore.  No client-side change needed; the URL still
points at one endpoint and the brain transparently uses the cluster.

Legacy /neuro/ask is still supported via the LEGACY_NEURO_API env var
for old setups that haven't migrated.
"""
from __future__ import annotations

import json
import os
import time
import uuid
from pathlib import Path
from typing import Any, Callable, Optional, Sequence


def _wizard_endpoint() -> str:
    """Brain-server URL, configurable via env.

    Default: http://localhost:8095 (the new W1z4rDV1510n brain server).
    Legacy: WIZARD_NODE_URL (port 8090, /neuro/ask) is honoured for
    backward compat — set WIZARD_BRAIN_URL or WIZARD_NODE_URL.  The
    Django wizard_chat app uses WIZARD_BRAIN_CHAT_URL; that takes
    precedence if set.
    """
    return (
        os.getenv("WIZARD_BRAIN_CHAT_URL")
        or os.getenv("WIZARD_BRAIN_URL")
        or os.getenv("WIZARD_NODE_URL")
        or "http://localhost:8095"
    )


def _wizard_timeout() -> float:
    try:
        return float(os.getenv("WIZARD_TIMEOUT_S", "30"))
    except Exception:
        return 30.0


def _legacy_neuro_api() -> bool:
    """Use the legacy /neuro/ask endpoint instead of /chat.

    Set `LEGACY_NEURO_API=1` for the old crates/core node on port 8090.
    The default is False; the new brain server at port 8095 uses /chat.
    """
    raw = os.getenv("LEGACY_NEURO_API", "").strip().lower()
    return raw in {"1", "true", "yes"}


class WizardSession:
    """
    AI session backed by the W1z4rD Vision Node at localhost:8090.

    The interface is intentionally identical to C0d3rSession.send() so that
    every place in the codebase that calls session.send(prompt, stream=False)
    works without modification.
    """

    MODEL_ID = "wizard-v1-local"

    def __init__(
        self,
        session_name: str = "wizard",
        *,
        endpoint: str | None = None,
        timeout_s: float | None = None,
        transcript_dir: str | Path | None = None,
        workdir: str | Path | None = None,
        meta_role: Optional[str] = None,
        # Accept and ignore Bedrock-specific kwargs so the factory can pass
        # them without conditional checks.
        **_ignored: Any,
    ) -> None:
        self.session_name = session_name
        self.endpoint = (endpoint or _wizard_endpoint()).rstrip("/")
        self.timeout_s = timeout_s if timeout_s is not None else _wizard_timeout()
        self.workdir = Path(workdir).resolve() if workdir else Path.cwd()
        self.meta_role = meta_role
        self._session_id = str(uuid.uuid4())
        self._transcript_dir = Path(transcript_dir) if transcript_dir else None
        if self._transcript_dir:
            self._transcript_dir.mkdir(parents=True, exist_ok=True)
        self._stream_callback: Optional[Callable[[str], None]] = None

    # ------------------------------------------------------------------
    # Core interface
    # ------------------------------------------------------------------

    def send(
        self,
        prompt: str,
        *,
        stream: bool = False,
        system: str = "",
        verbose: bool = False,
        research_override: bool = False,
        images: Optional[Sequence[str]] = None,
        stream_callback: Optional[Callable[[str], None]] = None,
        **_ignored: Any,
    ) -> str:
        """
        Send a prompt to the W1z4rD node and return the text response.

        system context is prepended to the prompt so the node can
        attempt to recall relevant knowledge from that framing.
        """
        if stream_callback is not None:
            self._stream_callback = stream_callback

        full_prompt = prompt.strip()
        if system and system.strip():
            full_prompt = f"[Context: {system.strip()[:2000]}]\n\n{full_prompt}"

        response = self._call_node(full_prompt)
        self._append_transcript(prompt, response)
        if stream and response:
            self._emit(response)
        return response

    # ------------------------------------------------------------------
    # Session metadata (matches C0d3rSession interface)
    # ------------------------------------------------------------------

    def get_model_id(self) -> str:
        return self.MODEL_ID

    @property
    def session_id(self) -> str:
        return self._session_id

    # ------------------------------------------------------------------
    # Node HTTP call
    # ------------------------------------------------------------------

    def _call_node(self, text: str) -> str:
        """Call POST /chat (or legacy /neuro/ask) and extract the answer.

        Endpoint selection per `LEGACY_NEURO_API` env var.  Default
        targets the new brain server at port 8095; set
        `LEGACY_NEURO_API=1` to fall back to the legacy port-8090 node.
        """
        import urllib.request
        import urllib.error

        if _legacy_neuro_api():
            url = f"{self.endpoint}/neuro/ask"
            payload = json.dumps({
                "text": text,
                "session_id": self._session_id,
                "top_k": 30,
                "min_strength": 0.05,
            }).encode()
        else:
            # New brain-server contract — /chat takes just {"text": ...}.
            url = f"{self.endpoint}/chat"
            payload = json.dumps({"text": text}).encode()

        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout_s) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
        except urllib.error.URLError as exc:
            return (
                f"[wizard-brain unavailable: {exc}] "
                f"The brain server is not running at {self.endpoint}. "
                "Start it with: w1z4rd_brain_server.exe "
                "(W1Z4RDV1510N_DATA_DIR=... W1Z4RD_BRAIN_PORT=8095)"
            )
        except Exception as exc:
            return f"[wizard-brain error: {exc}]"

        try:
            data = json.loads(raw)
        except Exception:
            return raw[:2000] if raw.strip() else "[wizard-brain: empty response]"

        # New brain-server /chat returns both `answer` and `reply`
        # (same content; alias for clients).  Legacy /neuro/ask returns
        # `answer` only.  Take whichever is non-empty.
        answer = str(data.get("answer") or data.get("reply") or "").strip()

        # When answer is empty (hypothesis / low confidence / OOG),
        # build a structured fallback so the agent gets SOMETHING.
        if not answer:
            grounding = data.get("grounding") or {}
            decoder = str(data.get("decoder") or "unknown")
            outside_grounding = bool(grounding.get("outside_grounding"))
            concepts = data.get("activated_concepts") or []
            # New brain server schema doesn't include confidence_tier;
            # use integrated_confidence as a numeric proxy.
            conf = grounding.get(
                "integrated_confidence",
                data.get("confidence_tier", 0.0),
            )

            if outside_grounding:
                answer = (
                    f"[wizard-brain OOG] decoder={decoder!r} confidence={conf!r}. "
                    "Honest grounding contract: the brain has not been trained "
                    "on this input; it refuses to fabricate.  Caller should "
                    "treat this as 'I don't know'."
                )
            elif concepts:
                concept_list = ", ".join(
                    str(c)
                    .replace("txt:word_", "")
                    .replace("txt:", "")
                    .replace("act:", "")
                    for c in concepts[:10]
                )
                answer = (
                    f"[wizard-brain hypothesis] decoder={decoder!r} "
                    f"confidence={conf!r}. Activated concepts: {concept_list}. "
                    "The brain has queued this question for future training."
                )
            else:
                answer = (
                    f"[wizard-brain hypothesis] No answer recalled "
                    f"(decoder={decoder!r}, confidence={conf!r}). "
                    "The brain may need more training on this topic."
                )

        return answer

    # ------------------------------------------------------------------
    # Utility
    # ------------------------------------------------------------------

    def _emit(self, text: str) -> None:
        if self._stream_callback:
            try:
                self._stream_callback(text)
            except Exception:
                pass

    def _append_transcript(self, prompt: str, response: str) -> None:
        if self._transcript_dir is None:
            return
        try:
            path = self._transcript_dir / f"{self.session_name}.log"
            ts = time.strftime("%Y-%m-%d %H:%M:%S")
            divider = "=" * 80
            with path.open("a", encoding="utf-8") as fh:
                fh.write(
                    f"{divider}\nTIMESTAMP: {ts}\nSESSION: {self.session_name}\n"
                    f"PROMPT:\n{prompt}\nRESPONSE:\n{response}\n"
                )
        except Exception:
            pass

    # ------------------------------------------------------------------
    # Health probe (called by setup script and diagnostics)
    # ------------------------------------------------------------------

    @classmethod
    def probe(cls, endpoint: str | None = None) -> dict:
        """
        Probe the node health endpoint.  Returns a dict with:
          online: bool, version: str, endpoint: str, error: str
        """
        import urllib.request
        import urllib.error

        ep = (endpoint or _wizard_endpoint()).rstrip("/")
        url = f"{ep}/health"
        try:
            with urllib.request.urlopen(url, timeout=5) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
            try:
                data = json.loads(raw)
            except Exception:
                data = {}
            return {"online": True, "endpoint": ep, "version": data.get("version", ""), "error": ""}
        except urllib.error.URLError as exc:
            return {"online": False, "endpoint": ep, "version": "", "error": str(exc)}
        except Exception as exc:
            return {"online": False, "endpoint": ep, "version": "", "error": str(exc)}
