"""tools/wizard_session.py — W1z4rD Vision Node AI backend.

Drop-in AI session that calls the W1z4rD node's /neuro/ask (also /chat)
endpoint instead of Bedrock or Codex CLI.  Matches the send() interface
used by C0d3rSession so it can be swapped in anywhere sessions are created.

The node uses Hebbian neural fabric — answers are recalled from trained
associations, not generated by a transformer.  This means:
  - Responses improve as the node trains on more data.
  - Structured JSON requests may not return valid JSON until training grows.
  - The agent's fallback mechanisms handle empty/hypothesis responses.

Endpoint contract:
  POST /neuro/ask  (or /chat)
  Request:  {"text": str, "session_id"?: str, "context"?: str}
  Response: {"answer": str, "hypothesis": bool,
             "activated_concepts": [str], "confidence_tier": str, ...}
"""
from __future__ import annotations

import json
import os
import time
import uuid
from pathlib import Path
from typing import Any, Callable, Optional, Sequence


def _wizard_endpoint() -> str:
    return os.getenv("WIZARD_NODE_URL", "http://localhost:8090")


def _wizard_timeout() -> float:
    try:
        return float(os.getenv("WIZARD_TIMEOUT_S", "30"))
    except Exception:
        return 30.0


class WizardSession:
    """
    AI session backed by the W1z4rD Vision Node at localhost:8090.

    The interface is intentionally identical to C0d3rSession.send() so that
    every place in the codebase that calls session.send(prompt, stream=False)
    works without modification.
    """

    MODEL_ID = "wizard-v1-local"

    def __init__(
        self,
        session_name: str = "wizard",
        *,
        endpoint: str | None = None,
        timeout_s: float | None = None,
        transcript_dir: str | Path | None = None,
        workdir: str | Path | None = None,
        meta_role: Optional[str] = None,
        # Accept and ignore Bedrock-specific kwargs so the factory can pass
        # them without conditional checks.
        **_ignored: Any,
    ) -> None:
        self.session_name = session_name
        self.endpoint = (endpoint or _wizard_endpoint()).rstrip("/")
        self.timeout_s = timeout_s if timeout_s is not None else _wizard_timeout()
        self.workdir = Path(workdir).resolve() if workdir else Path.cwd()
        self.meta_role = meta_role
        self._session_id = str(uuid.uuid4())
        self._transcript_dir = Path(transcript_dir) if transcript_dir else None
        if self._transcript_dir:
            self._transcript_dir.mkdir(parents=True, exist_ok=True)
        self._stream_callback: Optional[Callable[[str], None]] = None

    # ------------------------------------------------------------------
    # Core interface
    # ------------------------------------------------------------------

    def send(
        self,
        prompt: str,
        *,
        stream: bool = False,
        system: str = "",
        verbose: bool = False,
        research_override: bool = False,
        images: Optional[Sequence[str]] = None,
        stream_callback: Optional[Callable[[str], None]] = None,
        **_ignored: Any,
    ) -> str:
        """
        Send a prompt to the W1z4rD node and return the text response.

        system context is prepended to the prompt so the node can
        attempt to recall relevant knowledge from that framing.
        """
        if stream_callback is not None:
            self._stream_callback = stream_callback

        full_prompt = prompt.strip()
        if system and system.strip():
            full_prompt = f"[Context: {system.strip()[:2000]}]\n\n{full_prompt}"

        response = self._call_node(full_prompt)
        self._append_transcript(prompt, response)
        if stream and response:
            self._emit(response)
        return response

    # ------------------------------------------------------------------
    # Session metadata (matches C0d3rSession interface)
    # ------------------------------------------------------------------

    def get_model_id(self) -> str:
        return self.MODEL_ID

    @property
    def session_id(self) -> str:
        return self._session_id

    # ------------------------------------------------------------------
    # Node HTTP call
    # ------------------------------------------------------------------

    def _call_node(self, text: str) -> str:
        """Call POST /neuro/ask and extract the answer."""
        import urllib.request
        import urllib.error

        payload = json.dumps({
            "text": text,
            "session_id": self._session_id,
            "top_k": 30,
            "min_strength": 0.05,
        }).encode()

        url = f"{self.endpoint}/neuro/ask"
        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout_s) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
        except urllib.error.URLError as exc:
            return (
                f"[wizard-node unavailable: {exc}] "
                "The W1z4rD Vision Node is not running at "
                f"{self.endpoint}. Start it with: "
                "scripts/setup_wizard_node.py --start"
            )
        except Exception as exc:
            return f"[wizard-node error: {exc}]"

        try:
            data = json.loads(raw)
        except Exception:
            return raw[:2000] if raw.strip() else "[wizard-node: empty response]"

        # Primary answer field
        answer = str(data.get("answer") or "").strip()

        # If answer is empty (hypothesis / low confidence), build a fallback
        # from activated concepts so the agent always gets SOMETHING to work with.
        if not answer:
            concepts = data.get("activated_concepts") or []
            tier = data.get("confidence_tier", "uncertain")
            if concepts:
                concept_list = ", ".join(str(c).replace("txt:word_", "") for c in concepts[:10])
                answer = (
                    f"[wizard-node hypothesis] Activated concepts: {concept_list}. "
                    f"Confidence tier: {tier}. "
                    "The node has queued this question for future training."
                )
            else:
                answer = (
                    f"[wizard-node hypothesis] No answer recalled (tier: {tier}). "
                    "The node may need more training on this topic."
                )

        return answer

    # ------------------------------------------------------------------
    # Utility
    # ------------------------------------------------------------------

    def _emit(self, text: str) -> None:
        if self._stream_callback:
            try:
                self._stream_callback(text)
            except Exception:
                pass

    def _append_transcript(self, prompt: str, response: str) -> None:
        if self._transcript_dir is None:
            return
        try:
            path = self._transcript_dir / f"{self.session_name}.log"
            ts = time.strftime("%Y-%m-%d %H:%M:%S")
            divider = "=" * 80
            with path.open("a", encoding="utf-8") as fh:
                fh.write(
                    f"{divider}\nTIMESTAMP: {ts}\nSESSION: {self.session_name}\n"
                    f"PROMPT:\n{prompt}\nRESPONSE:\n{response}\n"
                )
        except Exception:
            pass

    # ------------------------------------------------------------------
    # Health probe (called by setup script and diagnostics)
    # ------------------------------------------------------------------

    @classmethod
    def probe(cls, endpoint: str | None = None) -> dict:
        """
        Probe the node health endpoint.  Returns a dict with:
          online: bool, version: str, endpoint: str, error: str
        """
        import urllib.request
        import urllib.error

        ep = (endpoint or _wizard_endpoint()).rstrip("/")
        url = f"{ep}/health"
        try:
            with urllib.request.urlopen(url, timeout=5) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
            try:
                data = json.loads(raw)
            except Exception:
                data = {}
            return {"online": True, "endpoint": ep, "version": data.get("version", ""), "error": ""}
        except urllib.error.URLError as exc:
            return {"online": False, "endpoint": ep, "version": "", "error": str(exc)}
        except Exception as exc:
            return {"online": False, "endpoint": ep, "version": "", "error": str(exc)}
