# Generated by Django 5.1.4 on 2026-03-12 15:23

import delegation.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResourceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=32, unique=True)),
                ('avg_duration_seconds', models.FloatField(default=0.0)),
                ('avg_peak_cpu_percent', models.FloatField(default=0.0)),
                ('avg_peak_memory_mb', models.FloatField(default=0.0)),
                ('sample_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DelegationHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the host', max_length=128)),
                ('host', models.CharField(help_text='hostname or IP', max_length=255)),
                ('port', models.IntegerField(default=7782)),
                ('api_token', models.CharField(default=delegation.models._gen_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pairing', 'Pairing'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='pairing', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('device_type', models.CharField(blank=True, default='', max_length=32)),
                ('os_name', models.CharField(blank=True, default='', max_length=64)),
                ('cpu_count', models.IntegerField(default=0)),
                ('total_memory_mb', models.IntegerField(default=0)),
                ('python_version', models.CharField(blank=True, default='', max_length=32)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_percent', models.FloatField(default=0.0)),
                ('memory_available_mb', models.IntegerField(default=0)),
                ('disk_free_mb', models.IntegerField(default=0)),
                ('max_concurrent_tasks', models.IntegerField(default=1)),
                ('active_tasks', models.IntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
                'unique_together': {('host', 'port')},
            },
        ),
        migrations.CreateModel(
            name='DelegatedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('data_ingest', 'OHLCV Data Download'), ('news_enrichment', 'News Enrichment'), ('dataset_warmup', 'Dataset Warmup'), ('candidate_training', 'Model Training'), ('ghost_metrics', 'Ghost Metrics'), ('ghost_trading', 'Ghost Trading'), ('live_monitoring', 'Live Price Monitoring'), ('background_refresh', 'Background Refresh')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='queued', max_length=16)),
                ('payload', models.JSONField(default=dict, help_text='Task parameters sent to the host')),
                ('api_keys_sent', models.JSONField(default=list, help_text='Which API key names were forwarded (not values)')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Result data from the host')),
                ('result_files', models.JSONField(blank=True, default=list, help_text='File paths of returned data')),
                ('error_message', models.TextField(blank=True, default='')),
                ('peak_cpu_percent', models.FloatField(default=0.0)),
                ('peak_memory_mb', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delegation.delegationhost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DelegationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('sent', 'Sent to Host'), ('received', 'Received from Host'), ('error', 'Error')], max_length=10)),
                ('message_type', models.CharField(max_length=64)),
                ('payload_summary', models.TextField(blank=True, default='')),
                ('payload_size_bytes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='delegation.delegationhost')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='delegation.delegatedtask')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='delegatedtask',
            index=models.Index(fields=['host', 'status'], name='delegation__host_id_e1a555_idx'),
        ),
        migrations.AddIndex(
            model_name='delegatedtask',
            index=models.Index(fields=['task_type', 'status'], name='delegation__task_ty_8766c5_idx'),
        ),
        migrations.AddIndex(
            model_name='delegationlog',
            index=models.Index(fields=['host', '-timestamp'], name='delegation__host_id_c5da16_idx'),
        ),
    ]
