# Generated by Django 5.1.4 on 2026-03-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegatedtask',
            name='remote_task_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='UUID sent to the remote host — used to poll for results', max_length=64),
        ),
    ]
