# Generated by Django 6.0.3 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('channel', models.CharField(db_index=True, max_length=64)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'connected_at'], name='serverless__channel_630a4e_idx')],
            },
        ),
    ]
