# Generated by Django 5.1.4 on 2026-02-08 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investigation_projects',
            },
        ),
        migrations.CreateModel(
            name='InvestigationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='person', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='investigations.investigationproject')),
            ],
            options={
                'db_table': 'investigation_entities',
            },
        ),
        migrations.CreateModel(
            name='InvestigationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='investigations.investigationproject')),
            ],
            options={
                'db_table': 'investigation_articles',
            },
        ),
        migrations.CreateModel(
            name='InvestigationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default='associated', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='investigations.investigationproject')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_links', to='investigations.investigationentity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_links', to='investigations.investigationentity')),
            ],
            options={
                'db_table': 'investigation_relations',
            },
        ),
        migrations.CreateModel(
            name='InvestigationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('requires_login', models.BooleanField(default=False)),
                ('login_url', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('crawl_policy', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='investigations.investigationproject')),
            ],
            options={
                'db_table': 'investigation_targets',
            },
        ),
        migrations.CreateModel(
            name='InvestigationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='')),
                ('title', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='investigations.investigationproject')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='investigations.investigationtarget')),
            ],
            options={
                'db_table': 'investigation_evidence',
            },
        ),
        migrations.AddIndex(
            model_name='investigationproject',
            index=models.Index(fields=['user', 'status'], name='investigati_user_id_f056fa_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationentity',
            index=models.Index(fields=['project', 'kind'], name='investigati_project_22ac6c_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationarticle',
            index=models.Index(fields=['project', 'status'], name='investigati_project_5e0bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationrelation',
            index=models.Index(fields=['project', 'relation_type'], name='investigati_project_ce6b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationtarget',
            index=models.Index(fields=['project', 'created_at'], name='investigati_project_b1ee6c_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationevidence',
            index=models.Index(fields=['project', 'captured_at'], name='investigati_project_d7138e_idx'),
        ),
    ]
